let data=JSON.parse(localStorage.getItem('insuranceData'))||[];let currentViewingIndex=null;let isAdmin=false;
function daysLeft(dateStr){const today=new Date();const target=new Date(dateStr);return Math.ceil((target-today)/(1000*60*60*24));}
function percentLeft(dateStr){const totalDays=30;if(!dateStr)return 0;const left=daysLeft(dateStr);return Math.max(0,Math.min(100,(left/totalDays)*100));}
function login(type){if(type==='admin'){let pass=prompt("أدخل كلمة المرور");if(pass!=='955783')return;isAdmin=true;}document.getElementById('intro-screen').style.display='none';document.getElementById('app').style.display='block';renderCards();}
function openForm(){if(!isAdmin)return;document.getElementById('form-modal').style.display='block';}
function closeForm(){document.getElementById('form-modal').style.display='none';}
function openImage(src,index){document.getElementById('image-modal').style.display='block';document.getElementById('modal-img').src=src;currentViewingIndex=index;}
function closeImage(){document.getElementById('image-modal').style.display='none';currentViewingIndex=null;}
function confirmRemoveVisible(){if(currentViewingIndex===null)return;if(confirm("هل تريد حذف التأمين؟")){deleteCard(currentViewingIndex);closeImage();}}
document.getElementById('insurance-form').addEventListener('submit',function(e){e.preventDefault();if(!isAdmin)return;let obj={name:document.getElementById('name').value,nationalId:document.getElementById('nationalId').value,category:document.getElementById('category').value,expiryDate:document.getElementById('expiryDate').value,image:document.getElementById('image').files[0]?URL.createObjectURL(document.getElementById('image').files[0]):''};data.push(obj);localStorage.setItem('insuranceData',JSON.string...
function renderCards(){let container=document.getElementById('cards-container');container.innerHTML='';data.forEach((item,i)=>{const left=daysLeft(item.expiryDate);let countdown=left>0?`باقي ${left} يوم`:'انتهى — رجاء التجديد';let color='green';if(left<=0)color='red';else if(left<=7)color='yellow';let barPercent=percentLeft(item.expiryDate);let card=document.createElement('div');card.className='card';card.innerHTML=`<img src="${item.image}" onclick="openImage('${item.image}',${i})"><h4>${item.name}</h4><...
function editCard(i){if(!isAdmin)return;let item=data[i];document.getElementById('name').value=item.name;document.getElementById('nationalId').value=item.nationalId;document.getElementById('category').value=item.category;document.getElementById('expiryDate').value=item.expiryDate;openForm();deleteCard(i);}
function deleteCard(i){if(!isAdmin)return;if(confirm("هل أنت متأكد من الحذف؟")){data.splice(i,1);localStorage.setItem('insuranceData',JSON.stringify(data));renderCards();}}
function clearAll(){if(!isAdmin)return;if(confirm("هل تريد حذف الكل؟")){data=[];localStorage.removeItem('insuranceData');renderCards();}}
function searchCards(){let val=document.getElementById('search').value;let container=document.getElementById('cards-container');container.innerHTML='';data.filter(item=>item.name.includes(val)||item.nationalId.includes(val)).forEach((item,i)=>{const left=daysLeft(item.expiryDate);let countdown=left>0?`باقي ${left} يوم`:'انتهى — رجاء التجديد';let color='green';if(left<=0)color='red';else if(left<=7)color='yellow';let barPercent=percentLeft(item.expiryDate);let card=document.createElement('div');card.class...
function filterCards(cat){let container=document.getElementById('cards-container');container.innerHTML='';data.filter(item=>cat==='all'||item.category===cat||(cat==='منتهي'&&daysLeft(item.expiryDate)<=0)).forEach((item,i)=>{const left=daysLeft(item.expiryDate);let countdown=left>0?`باقي ${left} يوم`:'انتهى — رجاء التجديد';let color='green';if(left<=0)color='red';else if(left<=7)color='yellow';let barPercent=percentLeft(item.expiryDate);let card=document.createElement('div');card.className='card';card.inn...
setInterval(renderCards,24*60*60*1000);